### ISSUE TITLE
Use external bin

### ISSUE THREAD

**Issue by MJBGO** [imagemin/imagemin-pngquant#36] opened 2017-03-14 12:46 UTC
Hi !

Is it possible to use an external executable of pngquant ? I'm trying to use this plugin but I'm facing a problem because the company in which I work doesn't allow any automatic downloads from github (only internal or npm repo) so it cannot found the exec file ...

Is there a way to use an existent build of pngquant (downloaded on the machine) or download it from another url that can be specified in the config ? This is possible in the grunt plugin but doesn't seem to be possible with this one ...

Thanks

**Comment by shinnn** [comment] 2017-06-05 08:59
Duplicate of https://github.com/imagemin/pngquant-bin/issues/66

**Closed by shinnn** 2017-06-05 08:59 UTC
